### ISSUE TITLE
Processing .cwa files from AX6 devices

### ISSUE THREAD

**Issue by claaslendt** [OxWearables/actipy#32]
Hi all,

I am currently processing AX6 data (acceleration and gyro). I was wondering if the read_device() function could be extended without too much effort to read the acceleration data from AX6 .cwa files as well. Right now, the function does work on these .cwa files but the resulting acceleration values in the pandas dataframe are incorrect.

**Comment by chanshing** [comment]
Hi @claaslendt, thanks for stopping by. Yes, it is our plan to do it, but we don't have a timeline yet, unfortunately. For the time being, the only option to use this package, if you're looking to use the calibration, nonwear detection and lowpass filter functionalities, is to first parse out the AX6 file as a CSV file (e.g. using the openmovement software https://github.com/digitalinteraction/openmovement) then use the functions in `actipy.processing.*` https://github.com/OxWearables/actipy?tab=readme-ov-file#usage I hope this helps!

**Comment by claaslendt** [comment]
Hi @chanshing! Thank you for the helpfulinfo and suggestions - that's what I have implemented as of now.
