### ISSUE TITLE
Add quality check outputs to actipy

### ISSUE THREAD

**Issue by aidanacquah** [OxWearables/actipy#36]
For epidemiological studies, there are quality checks made to wearable data.
For example, this can include calibration errors, wear time, 24 coverage and unrealistically high ENMO.

This is currently implemented in stepcount package. However, it may be useful to instead do this in the actipy package, to be shared across packages (asleep, stepcount, actinet etc.).

**Comment by chanshing** [comment]
https://github.com/OxWearables/actipy/pull/46
